(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var q;a:{var ba={Pa:!0},u={};try{u.__proto__=ba;q=u.Pa;break a}catch(a){}q=!1}k=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var v=k,ca=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");},da=ca(this);var ea={o:0,s:0,u:0,v:0,w:"#fff",A:"#fff",B:0,l:0,g:0,C:"0px",D:"0px",F:"0px",G:"0px",loop:!1,H:0,I:1,J:1,K:0,M:!1,shape:"square",O:1,P:1,R:0,S:0,i:0,j:0,$:"",N:!1,m:1,T:0,f:1,U:1},fa={o:0,s:0,u:280,v:260,w:"#fff",A:"#fff",B:0,l:.005,g:2,C:"100%",D:"0%",F:"10%",G:"0%",loop:!0,H:0,I:1,J:.1,K:0,M:!0,shape:"circle",O:12,P:8,R:0,S:0,i:2,j:1,$:"",N:!1,m:1,T:0,f:1,U:1},ha={o:0,s:.6,u:271,v:269,w:"#fff",A:"#fff",B:0,l:.01,g:2,C:"100%",D:"0%",F:"10%",G:"0%",loop:!0,H:0,I:1,J:.5,K:0,M:!0,shape:"line",O:25,
P:10,R:0,S:100,i:10,j:8,$:"",N:!1,m:1,T:0,f:1,U:1},ia={o:0,s:.6,u:100,v:80,w:"#ffdc00",A:"#dc000a",B:1.2,l:0,g:1,C:"20px",D:"10px",F:"40px",G:"35px",loop:!0,H:10,I:.3,J:.1,K:-.3,M:!1,shape:"teardrop",O:20,P:20,R:-30,S:100,i:1,j:.5,$:"",N:!0,m:20,T:.18,f:1,U:30},ja={o:0,s:.6,u:100,v:80,w:"#ffdc00",A:"#dc000a",B:1,l:0,g:2,C:"50px",D:"20px",F:"100px",G:"95px",loop:!0,H:15,I:.3,J:.1,K:-.3,M:!1,shape:"teardrop",O:40,P:40,R:-30,S:100,i:2,j:1,$:"",N:!0,m:20,T:.18,f:1,U:30},ka={o:0,s:.6,u:100,v:80,w:"#ffdc00",
A:"#dc000a",B:.8,l:0,g:4,C:"80px",D:"30px",F:"180px",G:"175px",loop:!0,H:15,I:.3,J:.1,K:-.3,M:!1,shape:"teardrop",O:100,P:100,R:-54,S:100,i:3,j:2,$:"",N:!0,m:20,T:.18,f:1,U:25},la={o:0,s:0,u:90,v:90,w:"#dcdcdc",A:"#dcdcdc",B:0,l:0,g:25,C:"22px",D:"10px",F:"120px",G:"100px",loop:!0,H:8,I:.03,J:.03,K:-.018,M:!0,shape:"teardrop",O:15,P:15,R:-.06,S:100,i:1,j:.8,$:"",N:!0,m:60,T:.6,f:.5,U:40},ma={o:0,s:.06,u:100,v:80,w:"#dcdcdc",A:"#dcdcdc",B:0,l:0,g:2,C:"35px",D:"10px",F:"150px",G:"148px",loop:!0,H:300,
I:.1,J:.1,K:-.03,M:!0,shape:"circle",O:20,P:10,R:-1.2,S:100,i:.8,j:.8,$:"",N:!0,m:10,T:0,f:.5,U:1};var w=function(a,b,d){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=d);return a},A=function(a,b,d){a=w(a,b,d);return 0<a?a:d},B=function(a,b,d){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=d);return a},C=function(a,b,d){return a.hasAttribute(b)?a.getAttribute(b):d},D=function(a,b,d){switch(a.getAttribute(b)){case "true":return!0;case "false":return!1;default:return d}};var na=/[^\d]+$/,G=function(a,b,d,c){if(!a.hasAttribute(b))return d;a=a.getAttribute(b);return isNaN(parseFloat(a))?d:E(a,c)},E=function(a,b){var d=parseFloat(a);(a=(a=a.match(na))&&a[0]||null)&&(a=a.trim());var c=d;"%"==a&&(c=Number((d/100*b).toFixed(2)));return c};var oa=/^#(?:[0-9a-f]{3}){1,2}$/i,pa=/#(.)(.)(.)/,H=[60,6E3],I=function(a){if(!oa.test(a))return null;4==a.length&&(a=a.replace(pa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},J=function(a,b,d,c,e){b=B(a,b,c);a=B(a,d,e);b>a&&(d=b,b=a,a=d);return[b,a]},qa=function(a){switch(a){case "snow":return fa;case "rain":return ha;case "fire-small":return ia;case "fire-medium":return ja;case "fire-large":return ka;case "steam":return la;case "smoke":return ma;default:return ea}},
K=function(a,b,d,c,e,f){b=G(a,b,c,f);a=G(a,d,e,f);b>a&&(d=b,b=a,a=d);return[b,a]};var L=function(a,b,d){return a+d*(b-a)},M=function(a){return a*a*a*(a*(6*a-15)+10)},P=function(a,b,d,c){switch(a%16){case 0:return b+d;case 1:return-b+d;case 2:return b-d;case 3:return-b-d;case 4:return b+c;case 5:return-b+c;case 6:return b-c;case 7:return-b-c;case 8:return d+c;case 9:return-d+c;case 10:return d-c;case 11:return-d-c;case 12:return b+d;case 13:return-d+c;case 14:return-b+d;case 15:return-d-c;default:return 0}},ra=function(){for(var a=Array(256),b=0;b<a.length;++b)a[b]=b;for(b=a.length-
1;0<b;--b){var d=Math.floor(Math.random()*a.length),c=a[b];a[b]=a[d];a[d]=c}this.Va=a.concat(a)},Q=function(a,b,d,c){var e=b&255,f=d&255,g=c&255;b-=Math.floor(b);d-=Math.floor(d);c-=Math.floor(c);var l=M(b),h=M(d);a=a.Va;return L(L(L(P(a[a[a[e]+f]+g],b,d,c),P(a[a[a[e+1]+f]+g],b-1,d,c),l),L(P(a[a[a[e]+f+1]+g],b,d-1,c),P(a[a[a[e+1]+f+1]+g],b-1,d-1,c),l),h),L(L(P(a[a[a[e]+f]+g+1],b,d,c-1),P(a[a[a[e+1]+f]+g+1],b-1,d,c-1),l),L(P(a[a[a[e]+f+1]+g+1],b,d-1,c-1),P(a[a[a[e+1]+f+1]+g+1],b-1,d-1,c-1),l),h),M(c))};var R=function(a){this.Ha=a;this.Ea=[];this.length=this.ka=0};R.prototype.get=function(a){return this.Ea[(a+this.ka)%this.length]};R.prototype.push=function(a){this.length<this.Ha&&this.length++;this.Ea[this.ka]=a;this.ka=(this.ka+1)%this.Ha};var sa=2*Math.PI,S=function(a,b){return a+Math.random()*(b-a)},U=function(a,b){this.h=[];this.b=b;this.c=a.getContext("2d");this.wa=window.devicePixelRatio;this.Ba=1;this.Fa=[];this.Ga=[];if("image"!=this.b.oa.shape)a=null;else if((a=this.b.oa.Ua)&&0!=a.length){b=[];this.Ba=this.b.na.max*this.wa;for(var d=0;d<a.length;d++){var c=a[d],e=document.createElement("canvas"),f=e.getContext("2d"),g=this.Ba/Math.max(c.naturalWidth,c.naturalHeight),l=c.naturalWidth*g;g*=c.naturalHeight;e.width=Math.ceil(l);
e.height=Math.ceil(g);f.drawImage(c,0,0,l,g);b.push(e);this.Fa.push(-l/2);this.Ga.push(-g/2)}a=b}else this.b.oa.shape="square",a=null;this.xa=a;this.la=0;this.Sa=0==this.b.g?this.b.za:1/this.b.g;a=this.b.ba;this.va=a.ga?0:(a.ja-a.sa)*a.Aa;this.ua=a.ga?0:(a.ia-a.ra)*a.Aa;this.ta=a.ga?0:(a.ha-a.qa)*a.Aa;this.Ca=(a=this.b.Ja)?new ra:null;this.Da=a?a.frequency:1;this.Za=a?a.Xa:1;this.Ka=a&&a.Ya-1||0;for(a=0;a<this.b.Ia;a++)T(this)};U.prototype.reset=function(){for(var a=this.la=this.h.length=0;a<this.b.Ia;a++)T(this)};
var V=function(a){var b=S(a.b.ma.Ma,a.b.ma.La),d=S(a.b.ma.Oa,a.b.ma.Na),c=S(a.b.na.min,a.b.na.max),e=S(a.b.ya.min,a.b.ya.max),f=a.b.ba,g=f.sa,l=f.ra,h=f.qa;f.ga&&(h=Math.random(),g=(1-h)*f.sa+h*f.ja,l=(1-h)*f.ra+h*f.ia,h=(1-h)*f.qa+h*f.ha);var n=S(a.b.pa.j,a.b.pa.i);f=S(a.b.pa.Ra,a.b.pa.Qa);var y=n*Math.cos(f);n*=Math.sin(f);var x=-1;a.xa&&(x=Math.floor(S(0,a.xa.length)));return{a:{positionX:b,positionY:d,size:c,X:g,W:l,V:h,opacity:e,da:!0,angle:f,ea:x},velocityX:y,velocityY:n,f:a.Za,aa:a.Ka?new R(a.Ka):
null}},T=function(a){for(var b=Date.now()/a.Da,d=0;d<a.h.length;d++){var c=a.h[d],e=a;c.aa&&c.aa.push({positionX:c.a.positionX,positionY:c.a.positionY,size:c.a.size,X:c.a.X,W:c.a.W,V:c.a.V,opacity:c.a.opacity,angle:c.a.angle,ea:c.a.ea,da:c.a.da});if(c.a.da){c.a.positionX+=c.velocityX;c.a.positionY+=c.velocityY;if(e.Ca&&0<c.f){var f=c.a.positionX/e.Da,g=c.a.positionY/e.Da;c.a.positionX+=c.f*Q(e.Ca,f,g,b);c.a.positionY+=c.f*Q(e.Ca,b,f,g);c.f+=e.b.Ja.rate}c.a.size+=e.b.na.rate;c.a.opacity=Math.min(1,
c.a.opacity+e.b.ya.rate);c.velocityX+=e.b.acceleration.x;c.velocityY+=e.b.acceleration.y;c.a.angle=Math.atan2(c.velocityY,c.velocityX);f=e.b.ba;f.ga||((!e.va||1<(f.ja-c.a.X)/e.va)&&(!e.ua||1<(f.ia-c.a.W)/e.ua)&&(!e.ta||1<(f.ha-c.a.V)/e.ta)?(c.a.X+=e.va,c.a.W+=e.ua,c.a.V+=e.ta):(c.a.X=e.b.ba.ja,c.a.W=e.b.ba.ia,c.a.V=e.b.ba.ha))}if(0>c.a.positionX+c.a.size||c.a.positionX-c.a.size>a.b.width||0>c.a.positionY+c.a.size||c.a.positionY-c.a.size>a.b.height||0>c.a.opacity||0>c.a.size)a.b.Wa?(c=c.aa,a.h[d]=
V(a),a.h[d].aa=c):c.a.da=!1}if(a.h.length<a.b.za)for(a.la=Math.min(a.la+a.Sa,a.b.za),b=Math.floor(a.la)-a.h.length,d=0;d<b;d++)a.h.push(V(a))},ta=function(a,b){if(b.da){a.c.fillStyle="rgba("+Math.round(b.X)+", "+Math.round(b.W)+", "+Math.round(b.V)+", "+b.opacity+")";a.c.save();a.c.translate(b.positionX,b.positionY);var d=b.size/a.Ba;a.c.scale(d,d);switch(a.b.oa.shape){case "circle":a.c.beginPath();a.c.arc(0,0,.5,0,sa);a.c.fill();break;case "line":a.c.beginPath();a.c.rotate(b.angle);a.c.fillRect(-.5,
-.01,1,.02);break;case "teardrop":a.c.beginPath();a.c.moveTo(.08,-.5);a.c.bezierCurveTo(.13,-.21,.16,.04,.3,.07);a.c.bezierCurveTo(.44,.36,.13,.5,-.06,.5);a.c.bezierCurveTo(-.49,.14,-.41,0,.08,-.5);a.c.fill();break;case "image":a.c.globalAlpha=b.opacity;a.c.drawImage(a.xa[b.ea],a.Fa[b.ea],a.Ga[b.ea]);break;default:a.c.beginPath(),a.c.fillRect(-.5,-.5,1,1)}a.c.restore()}};var ua=function(a,b){var d=void 0===d?null:d;var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,d);b.dispatchEvent(c)};var va=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},wa=function(a){if(va(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&va(a))return a;return null},xa=function(a){return(a=C(a,"sprite-image-src",""))?a.split(",").map(function(b){return b.trim()}):[]};var ya={$a:"acceleration-x",ab:"acceleration-y",bb:"angle-max",cb:"angle-min",eb:"autoplay",fb:"color1",gb:"color2",hb:"color-rate",ib:"custom-preset",jb:"emit-interval",kb:"emit-x-max",lb:"emit-x-min",mb:"emit-y-max",nb:"emit-y-min",ob:"loop",pb:"number",qb:"opacity-max",rb:"opacity-min",sb:"opacity-rate",tb:"preset-type",ub:"random-colors",vb:"shape",wb:"size-max",xb:"size-min",yb:"size-rate",zb:"skip-forward",Ab:"speed-max",Bb:"speed-min",Cb:"sprite-image-src",Db:"turbulence-frequency",Eb:"turbulence-rate",
Fb:"turbulence-strength",Gb:"turbulence-trail"},za=[],Aa=0,Ba;for(Ba in ya)za[Aa++]=ya[Ba];var W=function(){var a=HTMLElement.call(this)||this;a.L=null;a.Z=0;a.Y=[];a.ca=a.Ta.bind(a);a.fa=2;return a},X=HTMLElement;W.prototype=aa(X.prototype);W.prototype.constructor=W;if(v)v(W,X);else for(var Y in X)if("prototype"!=Y)if(Object.defineProperties){var Ca=Object.getOwnPropertyDescriptor(X,Y);Ca&&Object.defineProperty(W,Y,Ca)}else W[Y]=X[Y];W.prototype.attributeChangedCallback=function(){this.reset()};
W.prototype.connectedCallback=function(){if(!this.gwdIsLoaded()){var a=wa(this);a?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad()}};W.prototype.disconnectedCallback=function(){Z(this);this.L=null};W.prototype.gwdLoad=function(){if(!this.L){Z(this);var a=xa(this);if(this.Z=a.length)for(var b=0;b<this.Z;b++){var d=this.ownerDocument.createElement("img");d.addEventListener("load",this.ca,!1);d.addEventListener("error",this.ca,!1);d.src=a[b];this.Y.push(d)}0===this.Z&&Da(this)}};
W.prototype.gwdIsLoaded=function(){return!!this.L};
var Z=function(a){for(;a.Y.length;){var b=a.Y.pop();b.removeEventListener("load",a.ca,!1);b.removeEventListener("error",a.ca,!1)}a.Z=0},Da=function(a){var b=a.getAttribute("preset-type"),d=a.Y.length?a.Y:null;if(a.parentElement){var c=a.parentElement.getElementsByTagName("canvas")[0];if(c){var e=a.parentElement.clientWidth,f=a.parentElement.clientHeight;b=qa(b);var g=E(b.D,e),l=E(b.C,e),h=E(b.G,f),n=E(b.F,f);g=K(a,"emit-x-min","emit-x-max",g,l,e);h=K(a,"emit-y-min","emit-y-max",h,n,f);h={Ma:g[0],
La:g[1],Oa:h[0],Na:h[1]};n=b.H;b.l&&(n=Math.ceil(b.l*(h.La-h.Ma)*(h.Na-h.Oa)));n=Math.min(A(a,"number",n),1E3);g=A(a,"emit-interval",b.g);l=b.S;var y=w(a,"skip-forward",l);l=Math.round((0<=y?y:l)*Math.min(Math.max(n*g,H[0]),H[1])/100);y=D(a,"loop",b.loop);var x=J(a,"size-min","size-max",b.P,b.O),z=B(a,"size-rate",b.R)/60;x={min:x[0],max:x[1],rate:z};z=J(a,"opacity-min","opacity-max",b.J,b.I);var t=B(a,"opacity-rate",b.K)/60;z={min:z[0],max:z[1],rate:t};t=C(a,"color1",b.w);var r=C(a,"color2",b.A);
t=I(t);r=I(r);var m=D(a,"random-colors",b.M),p=B(a,"color-rate",b.B)/60;t={ga:m,sa:t[0],ra:t[1],qa:t[2],ja:r[0],ia:r[1],ha:r[2],Aa:p};r=J(a,"speed-min","speed-max",b.j,b.i);m=J(a,"angle-min","angle-max",b.v,b.u);m[0]=-m[0];m[1]=-m[1];r={j:r[0],i:r[1],Ra:m[1]/180*Math.PI,Qa:m[0]/180*Math.PI};m=B(a,"acceleration-x",b.o)/60;p=B(a,"acceleration-y",b.s)/60;m={x:m,y:p};p=C(a,"shape",b.shape);d={shape:p,Ua:"image"==p?d:null};p=a.hasAttribute("turbulence-frequency");var F=a.hasAttribute("turbulence-strength"),
N=a.hasAttribute("turbulence-rate"),O=a.hasAttribute("turbulence-trail");b.N||p||F||N||O?(p=B(a,"turbulence-frequency",b.m),F=B(a,"turbulence-strength",b.f),N=B(a,"turbulence-rate",b.T)/60,O=Math.min(A(a,"turbulence-trail",b.U),100),b={frequency:0<p?p:b.m,Xa:0<F?F:b.f,rate:N,Ya:O}):b=null;a.L=new U(c,{width:e,height:f,za:n,g:g,Ia:l,ma:h,na:x,ya:z,ba:t,pa:r,acceleration:m,Wa:y,oa:d,Ja:b});ua("ready",a)}}};
W.prototype.Ta=function(a){var b=a.target;b.removeEventListener("load",this.ca,!1);b.removeEventListener("error",this.ca,!1);b=this.Y.indexOf(b);0<=b&&("error"===a.type&&this.Y.splice(b,1),this.Z--);0===this.Z&&Da(this)};W.prototype.updateAndDraw=function(){0===this.fa&&T(this.L);if(2!=this.fa){var a=this.L;a.c.save();a.c.scale(a.wa,a.wa);for(var b=0;b<a.h.length;b++){var d=a.h[b];if(d.aa)for(var c=0;c<d.aa.length;c++)ta(a,d.aa.get(c));ta(a,d.a)}a.c.restore()}};
W.prototype.play=function(){this.fa=0};W.prototype.pause=function(){this.fa=1};W.prototype.stop=function(){this.fa=2;this.L.reset()};W.prototype.reset=function(){Z(this);this.L=null;ua("request-reload",this)};da.Object.defineProperties(W,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return za}}});customElements.define("gwd-particles",W);}).call(this);
